backbone: se-resnet50

m1: 1.
m2: .5
m3: 0.
s: 64.

img_width: 112
img_height: 112
embedding_size: 512
n_classes: 180855
steps_per_epoch: 5000
max_to_keep: 10

per_replica_batch_size: 64
test_batch_size: 64
initial_epoch: 0
epochs: 100
# learning_rate: 0.001
eval_every: 1
lfw_n_folds: 10

lr_steps: [10000]
lr_values: [0.001, 0.001]

data_dir: /mnt/disks/data/sirius/datasets/asian_and_msra_mtcnnpy_112_margin32
lfw_pairs: /mnt/disks/data/sirius/datasets/lfw-deepfunneled_mtcnnpy_112_margin32/pairs.txt
lfw_dir: /mnt/disks/data/sirius/datasets/lfw-deepfunneled_mtcnnpy_112_margin32

ckpt_dir: /home/peeranat_absoroute_io/trained_models/arcface_models/seresnet50_asian_msra_06042020
logdir: /home/peeranat_absoroute_io/trained_models/arcface_models/seresnet50_asian_msra_06042020/logs